import type { BackendModule, ReadCallback } from 'i18next';

/**
 * i18next backend that resolves (language, namespace) pairs against the
 * JSON files generated by `php artisan translations:generate`. Vite turns
 * every file matched by the glob into a lazy, content-hashed chunk, so
 * namespaces are fetched on demand and cached by the browser.
 */
const modules = import.meta.glob('../locales/*/*.json', { import: 'default' });

export const lazyImportBackend: BackendModule = {
  type: 'backend',

  init: () => undefined,

  read(language: string, namespace: string, callback: ReadCallback) {
    const load = modules[`../locales/${language}/${namespace}.json`];

    if (!load) {
      callback(new Error(`Missing translations for ${language}/${namespace}`), false);
      return;
    }

    load()
      .then((resources) => callback(null, resources as never))
      .catch((error: unknown) => callback(error as Error, false));
  },
};
