<?php

namespace Scrapkit\LocalizationI18n\Export;

class TypeScriptTypesGenerator
{
    /**
     * Build an i18next module augmentation that types t() keys against
     * the generated JSON of the default locale.
     *
     * @param  list<string>  $namespaces
     */
    public function generate(array $namespaces, string $defaultLocale, string $defaultNamespace): string
    {
        $resources = implode("\n", array_map(
            fn (string $namespace): string => "      '{$namespace}': typeof import('./{$defaultLocale}/{$namespace}.json');",
            $namespaces
        ));

        return <<<TYPESCRIPT
        // Auto-generated by translations:generate. Do not edit.
        import 'i18next';

        declare module 'i18next' {
          interface CustomTypeOptions {
            defaultNS: '{$defaultNamespace}';
            resources: {
        {$resources}
            };
          }
        }

        TYPESCRIPT;
    }
}
